# Generated by Django 2.2.10 on 2020-03-24 14:51

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0003_auto_20200323_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attach',
            field=models.FileField(blank=True, upload_to=course.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
